### ISSUE TITLE
ubuntu 上的训练图像一直imread不进去

### ISSUE THREAD

**Issue by janicevidal** [zhanglaplace/3000fps-mtcnn#1]
cmake ..  make 之后，prepare阶段图像imread读不进去，不清楚什么原因 ，图像路径没有错，绝对路径相对路径都有试过

**Comment by zhanglaplace** [comment]
@janicevidal 
https://github.com/zhanglaplace/3000fps-mtcnn/blob/master/ubuntu/src/prepare.cpp#L84
尝试从这里看下，解析的是否有问题

**Comment by janicevidal** [comment]
@zhanglaplace 找到原因了，准备的txt文件当中的回车符，和代码fgets循环中的读取有冲突，谢谢！
